# Site settings
title: Syntropy
email: contact@syntropy.io
description: "
  Syntropy is a software development company based in Morgantown, West Virginia that builds apps to help build your business.
  We specialize in using web, iPhone, iPad and Android to connect with customers and automate business processes.
  "

baseurl: ""
url: "http://syntropy.io"

twitter_username: SyntropyDev
github_username:  SyntropyDev
facebook_username: syntropydevelopment
plus_page: https://plus.google.com/116023901843696548502
contact_phone: +1 (304) 212-3444
contact_email: contact@syntropy.io

contact_form_method: POST
contact_form_redirect_url: http://syntropydev.github.io/thanks/
contact_form_action_url: ////forms.brace.io/sam@syntropy.io

hours: "9am - 6pm"
google_map_url: "https://www.google.com/maps/embed/v1/place?q=5005%20Mid-Atlantic%20Road%2C%20Morgantown%2C%20WV%2C%20United%20States&key=AIzaSyDS756UNHBCS5CSftugfayC-zTLwKCX_YY"
primary_location:
  name: Morgantown, WV
  street: 5005 Mid-Atlantic Road
  city: Morgantown
  state: WV
  zip: 26508


other_locations:
    - name: Charleston, WV
      street: 818 Oakwood Road
      city: Charleston
      state: WV
      zip: "25314"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: numeric

timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

