# Site settings
title: - Custom apps for your business
email: contact@syntropy.io
description: "
    Automate your business and reach new customers with custom software from Syntropy. We help clients automate paperwork, launch products, measure business analytics and track assets with custom iOS, Android, and web applications.
    Based in Morgantown, West Virginia.
  "

baseurl: ""
url: "http://syntropy.io"

twitter_username: SyntropyDev
github_username:  SyntropyDev
facebook_username: syntropydevelopment
plus_page: https://plus.google.com/116023901843696548502
contact_phone: +1 (304) 212-3444
contact_email: contact@syntropy.io

contact_form_method: POST
contact_form_redirect_url: http://syntropydev.github.io/thanks/
contact_form_action_url: ////forms.brace.io/sam@syntropy.io

hours: "9am - 6pm"
google_map_url: "https://www.google.com/maps/embed/v1/place?q=5005%20Mid-Atlantic%20Road%2C%20Morgantown%2C%20WV%2C%20United%20States&key=AIzaSyDS756UNHBCS5CSftugfayC-zTLwKCX_YY"
primary_location:
  name: Morgantown, WV
  street: 5005 Mid-Atlantic Road
  city: Morgantown
  state: WV
  zip: 26508


other_locations:
    - name: Charleston, WV
      street: 818 Oakwood Road
      city: Charleston
      state: WV
      zip: "25314"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: numeric

timezone: America/New_York

markdown: kramdown
permalink: pretty

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

